---
couchpotato_enabled: false
couchpotato_available_externally: false
couchpotato_container_name: couchpotato
couchpotato_container_store: linuxserver
couchpotato_config_directory: "{{ docker_app_data }}/couchpotato"
couchpotato_version: latest
couchpotato_port: "5050"
couchpotato_hostname: couchpotato
couchpotato_memory: 1g
