---

- name: Create tandoor group
  group:
    name: tandoor
    gid: "{{ tandoor_gid }}"
    state: present

- name: Create tandoor user
  user:
    name: tandoor
    uid: "{{ tandoor_uid }}"
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: tandoor
    
- name: Create tandoor directories
  file:
    path: "{{ item }}"
    state: directory
    owner: tandoor
    group: tandoor
    mode: 0755
  with_items:
    - "{{ tandoor_config_directory }}"

- name: Install tandoor Docker Container
  docker_container:
    name: "{{ tandoor_container_name }}"
    image: "{{ tandoor_container_store }}/{{ tandoor_container_name }}:{{ tandoor_version }}"
    pull: true
    volumes:
      - "{{ tandoor_config_directory }}:/config"
      - "{{ docker_app_data }}/shared:/shared"
    ports:
      - "{{ tandoor_port_http }}:80"
      - "{{ tandoor_port_https }}:443"
    env:
      TZ: "{{ system.timezone }}"
      PUID: "{{ heimdall_user_id | string }}"
      PGID: "{{ heimdall_user_id | string }}"
    restart_policy: unless-stopped
    memory: "{{ tandoor_memory }}"
    labels:
      traefik.enable: "{{ tandoor_available_externally }}"
      traefik.http.routers.tandoor.rule: "Host(`{{ tandoor_hostname }}.{{ external_domain }}`)"
      traefik.http.routers.tandoor.tls.certresolver: "letsencrypt"
      traefik.http.routers.tandoor.tls.domains[0].main: "{{ external_domain }}"
      traefik.http.routers.tandoor.tls.domains[0].sans: "*.{{ external_domain }}"
      traefik.http.services.tandoor.loadbalancer.server.port: "80"
